DROP USER SWING8 CASCADE;
CREATE USER SWING8 IDENTIFIED BY SWING8;
GRANT CONNECT, RESOURCE TO SWING8;

CONNECT SWING8/SWING8

DROP TABLE LIVRO CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_LIVRO;

CREATE SEQUENCE SEQ_LIVRO;

CREATE TABLE LIVRO
(NUMERO         NUMBER(5)
   CONSTRAINT LIVRO_ID_PK
   PRIMARY KEY,
 TITULO           VARCHAR2(50) 
   CONSTRAINT LIVRO_TITULO_NN
   NOT NULL,
 AUTOR           VARCHAR2(30)
   CONSTRAINT LIVRO_AUTOR_NN
   NOT NULL,
 TIPO         NUMBER(1)
   CONSTRAINT LIVRO_TIPO_NN
   NOT NULL,
 EDITORA      VARCHAR2(20)
   CONSTRAINT LIVRO_EDITORA_NN
   NOT NULL,
 PRECO      FLOAT
   CONSTRAINT LIVRO_PRECO_NN
   NOT NULL);
	   
INSERT INTO LIVRO(NUMERO, TITULO, AUTOR, TIPO, EDITORA, PRECO)
VALUES(SEQ_LIVRO.NEXTVAL, 'AS CRONICAS DE GELO E FOGO : O JOGO DOS TRONOS', 'GEORGE R.R MARTIN', 1, 'LEYA', 65.7);

INSERT INTO LIVRO(NUMERO, TITULO, AUTOR, TIPO, EDITORA, PRECO)
VALUES(SEQ_LIVRO.NEXTVAL, 'HARRY POTTER E A PEDRA FILOSOFAL', 'J.K ROLLING', 1, 'ROCCO', 45.6);

INSERT INTO LIVRO(NUMERO, TITULO, AUTOR, TIPO, EDITORA, PRECO)
VALUES(SEQ_LIVRO.NEXTVAL, 'HARRY POTTER E A CAMARA SECRETA', 'J.K ROLLING', 1, 'ROCCO', 45.6);

UPDATE LIVRO SET TITULO = UPPER(TITULO);


DROP TABLE AUTOR CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_AUTOR;

CREATE SEQUENCE SEQ_AUTOR;

CREATE TABLE AUTOR
(NUMERO         NUMBER(5)
   CONSTRAINT AUTOR_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30) 
   CONSTRAINT AUTOR_NOME_NN
   NOT NULL,
 SEXO           CHAR(1)
   CONSTRAINT AUTOR_SEXO_NN
   NOT NULL,
 IDADE          NUMBER(1)
   CONSTRAINT AUTOR_IDADE_NN
   NOT NULL,
 NACIONALIDADE           VARCHAR2(20) 
   CONSTRAINT NACIONALIDADE_NOME_NN
   NOT NULL);

INSERT INTO AUTOR(NUMERO, NOME, SEXO, IDADE, NACIONALIDADE)
VALUES(SEQ_AUTOR.NEXTVAL, 'GEORGE R.R MARTIN', 'M', 3, 'Britanico');

INSERT INTO AUTOR(NUMERO, NOME, SEXO, IDADE, NACIONALIDADE)
VALUES(SEQ_AUTOR.NEXTVAL, 'J.K ROLLING', 'F', 3, 'Britanica');

INSERT INTO AUTOR(NUMERO, NOME, SEXO, IDADE, NACIONALIDADE)
VALUES(SEQ_AUTOR.NEXTVAL, 'PAULO COELHO', 'M', 4, 'Brasileiro');

INSERT INTO AUTOR(NUMERO, NOME, SEXO, IDADE, NACIONALIDADE)
VALUES(SEQ_AUTOR.NEXTVAL, 'HARUKI MURAKAMA', 'M', 3, 'Japones');

INSERT INTO AUTOR(NUMERO, NOME, SEXO, IDADE, NACIONALIDADE)
VALUES(SEQ_AUTOR.NEXTVAL, 'JORGE LUIZ BORGES', 'M', 4, 'Argentino');

COMMIT;
